#!/usr/bin/env bash
# Allow the kadx user to run common network-scanning tools without a
# password prompt. This lets ShadowOps presets / form-builder commands
# that need root run end-to-end inside the xterm terminal without
# stopping for a sudo password.
#
# Run:  sudo bash ~/portable-pivot/backend/setup-passwordless-sudo.sh
#
# Each binary path is resolved at install time (and re-resolved if you
# re-run this) so it works on any path nmap etc. happens to live at.

set -euo pipefail

USER_NAME="${SUDO_USER:-kadx}"
SUDOERS_FILE=/etc/sudoers.d/shadowops-tools

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: run with sudo. Try:  sudo bash $0"
    exit 1
fi

TOOLS=(nmap arp-scan masscan fping netdiscover hping3 nbtscan tcpdump tshark)
RESOLVED=()
for t in "${TOOLS[@]}"; do
    p="$(command -v "$t" || true)"
    if [[ -n "$p" ]]; then
        RESOLVED+=("$p")
    else
        echo "  skipping $t (not installed)"
    fi
done

if [[ ${#RESOLVED[@]} -eq 0 ]]; then
    echo "ERROR: none of the expected tools are installed"
    exit 2
fi

JOINED="$(IFS=, ; echo "${RESOLVED[*]}")"

cat > "$SUDOERS_FILE" <<EOF
# Generated by setup-passwordless-sudo.sh on $(date -Iseconds)
# Allow the ShadowOps user to run network scanning tools without a password.
# Tools restricted by absolute path; arguments are unrestricted (typical for
# scanning tools). Each binary will only be invocable via sudo by this user.
$USER_NAME ALL=(root) NOPASSWD: $JOINED
EOF
chmod 0440 "$SUDOERS_FILE"

echo "==> Validating sudoers syntax"
visudo -c -f "$SUDOERS_FILE"

echo
echo "================================================================"
echo "Done. The user '$USER_NAME' can now run these without a password:"
echo "$JOINED" | tr , '\n' | sed 's|^|  |'
echo
echo "Test (in a fresh terminal, not this one):"
echo "  sudo -n nmap --version | head -1"
echo
echo "To revoke:  sudo rm $SUDOERS_FILE"
echo "================================================================"
